### ISSUE TITLE
KSC Island Tours: Seaplane: Flight 38 - Explore Random 2-6 passengers

### ISSUE THREAD

**Issue by inigma2** [inigmatus/GAP#11]

**Comment by inigmatus** [comment]
easy peasy.

**Comment by inigma2** [comment]
Got it working with data>int>numPassengers passing to Behavior>SpawnPassengers>count but this completely removes those spawned kerbals from any NewKerbal() function. Submitted support request asking if its possible to generate a random list of NewKerbal() kerbals and use that randomized list dynamically in SpawnPassengers: http://forum.kerbalspaceprogram.com/index.php?/topic/91625-105-contract-configurator-v183-2015-11-24/&page=81#comment-2307187

**Comment by inigma2** [comment]
```
DATA
{
     type = int
     numPassengers = Random(2,6)
}

DATA
{
    type = List<Kerbal>
    kerbals = [ NewKerbal(), NewKerbal(), NewKerbal(), NewKerbal(), NewKerbal(), NewKerbal() ].Random(@numPassengers)
}

BEHAVIOUR
{
    name = SpawnPassengers
    type = SpawnPassengers

    passengerName = @/kerbals

    kerbalType = Crew
}
```

nightingale is working on https://github.com/jrossignol/ContractConfigurator/issues/378 to add NewKerbal() list processing to SpawnPassengers.

**Comment by inigma2** [comment]
done in 0.3
