### ISSUE TITLE
KSC IslandTours: Flight 38 DestroyVessel Behavior on Recovery Causing Ghosted Recovery Hang in Space Center View

### ISSUE THREAD

**Issue by inigma2** [inigmatus/GAP#15]
wasn't gonna mention this. poor Nightingale already was swamped with 1.9.0 stuff.  Could be a critical bug. Needs test case and submission. Will be kind and wait to mention it to him until I have give him a tidy package.

I think it's related to the behavior changes KSP made on contract completion that was affecting kerbals not getting removed after contract completion. now vessels are not getting removed after contract completion. I tried using DestroyVessel to do the clean up, but it causes a weird bug where if the contract completes on RecoverVessel (not related to those intended to be destroyed), the recovered vessel appears near the admin building in Space Center view waiting to be recovered there, and freezes Space Center until you do so.

**Comment by inigma2** [comment]
Steps: 
1. uncomment DestroyVessel lines in IslandTours-2-ThreeHourTour.cfg
2. load Three Hour Tour contract.
3. Complete the parameters prior to recovery.
4. Recover your plane or ship that you used to transport the passengers (not one to be destroyed) to complete the contract.

The recovered ship gets warped to Space Center by admin building awaiting recovery. Space Center is hung until you do.

**Comment by inigma2** [comment]
Possible conflict with VesselNotDestroy?

**Comment by jrossignol** [comment]
This was a highly annoying stock bug, but I've managed to hack around it.  Ghost markers (which allow free recovery funds!) shall no longer plague you.

**Comment by inigma2** [comment]
tested and confirmed fixed. thank you!
