### ISSUE TITLE
GAP - KSP-AVC

### ISSUE THREAD

**Issue by inigma2** [inigmatus/GAP#151]
Apparently some people like KSP-AVC more than CKAN. Can't we all just get along and pick one master mod installer/version checker thingy? 

I was hoping to start a revolution by being the first majorly awesome mod to NOT support the ancient KSP-AVC method of mod up-to-date coolness, and be a mod evangelist for CKAN.  I guess those dreams will have to wait: http://forum.kerbalspaceprogram.com/index.php?/topic/91625-105-contract-configurator-v1931-2016-01-11/&do=findComment&comment=2363540

**Comment by jrossignol** [comment]
The best thing about KSP-AVC is you can set CKAN up to read your KSP-AVC file - and not ever have to worry about messing around with CKAN after the initial setup. ;)

**Comment by inigma2** [comment]
thanks! i'll roll it out on a GAP 2.0 completion. maybe earlier. I have a pretty full GAP development plate.

**Comment by inigma2** [comment]
done for 1.2
