### ISSUE TITLE
Airlines-Flight-4 - Pick Up Passengers at Terminal

### ISSUE THREAD

**Issue by inigma2** [inigmatus/GAP#159]
I do still want at least one plane contract where you have to go pick up 2-4 passengers at the Spaceplane Hangar Air Terminal (the field between the SPH and the adjacent runway fuel tanks. Perhaps just two of the 5 airline contract types:

Airlines-Flight-5 - KSC Airlines: Charter Flight 5 - Seats: 2-4
Airlines-Flight-10 - KSC Airlines: Charter Flight 10 - Seats: 2-4 (require mk1 Crew Cabin)

would require passenger pickup at the air terminal (and subsequent unloading as well) and thus simulate the manual loading of planes real life early aviation required before easier terminal loading was developed.

but the next level of airline contracts

Airlines-Flight-20 - KSC Airlines: Charter Flight 20 - Seats: 4-8
Airlines-Flight-40 - KSC Airlines: Charter Flight 40 - Seats: 2-8 (for science)
Airlines-Flight-101 - KSC Airlines: Flight 101-103 - Seats: 8-80

would be exempt from doing so.

All five contract types are repeatable, so players will simply want to ignore the flights 5 and 10 and stick with higher numbers to avoid the trip to the SPH.

Does this sound like a good mix?  And to make it more clear, I could drop the word "Charter" from flights that don't require a manual pickup of outbound passengers.

**Comment by inigma2** [comment]
I might consider actually just adding another flight. I added Airlines-Flight-4 to test.

At this point, until https://github.com/jrossignol/ContractConfigurator/issues/401 is coded, I think I will only have just one SPH air terminal passenger pickup contract. I really would like to randomize how many Kerbals are spawned on the field, and when it's ready I'll prob code Flights 5, 10, and 40 to do so and drop Flight 4 altogether.

**Comment by inigmatus** [comment]
Nightingale says f RemoteTech is throwing an exception on transmit, then it is a RemoteTech problem.
