### ISSUE TITLE
SSI-Loan - loan player StartingFunds at 25% interest

### ISSUE THREAD

**Issue by inigma2** [inigmatus/GAP#183]
I'm currently running into a bug with advanceFunds, where if rewardFunds has a negative reward, any amount in advanceFunds over 0 will immediately cause failureFunds to populate with advanceFunds (but negative as expected) even if failureFunds is programmed at 0. 

Any amount therefore in advanceFunds when rewardFunds is negative, will fail the contract on acceptance, ignoring the Timer parameter I set.  There is no way around this I can think of. Opening issue with CC.

**Comment by inigma2** [comment]
raised https://github.com/jrossignol/ContractConfigurator/issues/480

**Comment by inigmatus** [comment]
not duplicatable in CC 1.1.10
