### ISSUE TITLE
CoastGuard: Add K2 top side contract for medium difficulty.

### ISSUE THREAD

**Issue by jakkarth** [inigmatus/GAP#189]
I accepted a contract to rescue some climbers from the top of K2, but when I arrived they had spawned on the cliff face. When I switched to them, they lost traction, fell and died. The contract failed. Perhaps position coded into contract needs adjusting?

**Comment by inigma2** [comment]
They are supposed to be on the cliff face below the top of K2. It's slippery for sure, but should give them enough traction to stay on. Can you reload your mission and try again? It's possible the terrain didn't generate properly before they spawned for you.

**Comment by jakkarth** [comment]
If that's the intended behavior, then I have no idea how to complete the contract. They can't walk up the steep surface, and I can't land on the surface to rescue them, and there's no ledge below them they could slide down onto safely. I guess if I had KAS installed I could harpoon the top of the mountain and then winch my rescue craft down the face to them, but I didn't have any of that technology unlocked when I accepted the contract. Sadly I don't have a save from before the mission failed.

**Comment by inigma2** [comment]
The cliff face is not landable.. easily, though in stock it is possible, but requires some fancy engineering of a VTOL. The easier idea is to use a VTOL or helicopter with a KAS winch and ladder. Good luck. It's a very difficult mission.  I suppose I could develop an easier mission to allow players to simply pick up climbers stuck at the top of K2, where it's landable. :D  I'll include that as an enhancement for 1.3.

**Comment by inigma2** [comment]
Actually the easiest way is to land a rescue craft on the top of K2, and winch down to the area.

**Comment by jakkarth** [comment]
I guess I figured it'd be as easy as the "rescue guy from ocean" contract I had done previously, so I didn't expect it to be such a large jump in difficulty and assumed it was a bug. If the contract comes around again I'll give it another try. Everything else in this pack has been fantastic. Thanks for your hard work, and for the quick response. I look forward to more awesomeness in the next release :)

**Comment by inigma2** [comment]
Thanks for the feedback! 

I am reopening 'cause I want to track this as an enhancement for 1.3.

**Comment by inigma2** [comment]
added!
