### ISSUE TITLE
Air Flights not working with OPT parts

### ISSUE THREAD

**Issue by GerkinDev** [inigmatus/GAP#200]
Hi there,
First, thank you for this great contract pack, it really encourages us to use low/med level planes, and not starting using them for SSTO only, and this is great.

My problem is that i'm also a big fan of OPT Spaceplane mod, which adds some crew cabins. Those cabins works well with *Air Charter* missions, but not with *Air Flights*. Maybe it is related to the name of the part (IE, in my case, "OPT J Crew Tank")?

Is that behavior intended to allow only stock parts? If that is not the case, can you please fix the problem? My plane is at the hangar waiting for being used ;)

**Comment by inigma2** [comment]
cabins are no longer a requirement.
