### ISSUE TITLE
GAP does not work with AtmosphereAutopilot installed - solution

### ISSUE THREAD

**Issue by DrRaphello** [inigmatus/GAP#202]
With AA installed, First Flight and Glider contracts will never fulfill their requirements and will never be given to a player. A fix is to make GAP reckognize the different module name with AA installed.

This piece of code makes GAP AA-aware and allows both mods to coexist:
````
REQUIREMENT:NEEDS[AtmosphereAutopilot]
{
name = PartModuleUnlocked
type = PartModuleUnlocked
partModule = SyncModuleControlSurface
}
````

It needs to be added to files:
ContractPacks\GAP\Milestones (GAP Core)\Wright-FirstFlight.cfg 
ContractPacks\GAP\Milestones (GAP Core)\Wright-Glider.cfg
 right after this code:

````
REQUIREMENT
{
name = PartModuleUnlocked
type = PartModuleUnlocked

partModule = ModuleControlSurface
}
````

**Comment by inigma2** [comment]
Thanks for the code suggestion. Makes adding this much easier. :)

**Comment by inigma2** [comment]
Done. Added for next release.
