### ISSUE TITLE
"Give an airplane ride - Passengers: N" contracts always instantly fail.

### ISSUE THREAD

**Issue by TangentFoxy** [inigmatus/GAP#218]
Whether I start with the passenger(s) in the aircraft or launch without them on-board, any time I load a plane after accepting a passenger contract, it instantly fails. I am using a pilot and have seats available, it has wings, nothing happens that isn't allowed to happen.. it just fails on loading the vessel every time.

**Comment by inigma2** [comment]
Try with new contract configurator 2.11. See README in latest release.
